app = "stemsplitter-bhavin"
primary_region = "iad"

[build]
  dockerfile = "Dockerfile"

[env]
  WEB_JOBS_ROOT = "/data/web_jobs"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = "stop"
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[mounts]]
  source = "stems_data"
  destination = "/data"
